{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# \ud83d\udee1\ufe0f Agent Engineering Challenge\n",
    "\n",
    "**Duration:** 90 minutes &nbsp;|&nbsp; **Teams of 3\u20134** &nbsp;|&nbsp; **Claude Messages API or Agent SDK**\n",
    "\n",
    "---\n",
    "\n",
    "## What You're Building\n",
    "\n",
    "An AI agent that automates RFP (Request for Proposal) responses for a cybersecurity vendor. Your agent will:\n",
    "\n",
    "1. **Parse** a questionnaire into categorized questions\n",
    "2. **Retrieve** relevant source material from a knowledge base\n",
    "3. **Draft** polished, cited answers\n",
    "4. **Review** answers for cross-question consistency\n",
    "5. **Export** structured JSON output\n",
    "\n",
    "At the end, your team demos the agent live and explains your design decisions.\n",
    "\n",
    "### How You'll Be Evaluated\n",
    "\n",
    "| Criterion | Weight | What \"Excellent\" Looks Like |\n",
    "|-----------|--------|----------------------------|\n",
    "| **Agent Quality** | 60% | Clean tool design, effective prompts, structured JSON output, handles edge cases, review step catches inconsistencies |\n",
    "| **Demo Clarity** | 40% | Clear architecture walkthrough, live run on a fresh RFP, honest retrospective on tradeoffs |\n",
    "\n",
    "**Stretch goal (unscored but impressive):** Build eval assertions that validate your agent's output quality.\n",
    "\n",
    "### Suggested Time Allocation\n",
    "\n",
    "| Phase | Duration | Focus |\n",
    "|-------|----------|-------|\n",
    "| Setup & Planning | 5 min | Verify API, assign roles, sketch architecture |\n",
    "| Build | 65 min | Agent loop, prompt design, testing |\n",
    "| Demo Prep | 5 min | Prepare your walkthrough |\n",
    "| Demos | 15 min | Live presentations (3 min per team) |"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## Part 0: Environment Setup\n",
    "\n",
    "Run the cells below to install dependencies and verify your API connection."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Install dependencies\n!pip install anthropic --upgrade -q\n\nprint(\"\u2713 Dependencies installed\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\nimport json\nfrom typing import Optional\n\nimport anthropic\n\n# === API KEY SETUP ===\nANTHROPIC_API_KEY = \"\"  # <-- Paste your Anthropic API key here\n\nif not ANTHROPIC_API_KEY:\n    raise ValueError(\n        \"\u274c ANTHROPIC_API_KEY not found.\\n\"\n        \"Set it via: export ANTHROPIC_API_KEY='your-key-here'\\n\"\n        \"Or paste directly in the cell above.\"\n    )\n\nclient = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)\nprint(\"\u2713 Anthropic client initialized\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Verify API connectivity\n",
    "try:\n",
    "    response = client.messages.create(\n",
    "        model=\"claude-sonnet-4-20250514\",\n",
    "        max_tokens=20,\n",
    "        messages=[{\"role\": \"user\", \"content\": \"Say 'ready' and nothing else.\"}]\n",
    "    )\n",
    "    print(f\"\u2713 API connection verified: {response.content[0].text}\")\n",
    "    print(f\"  Model: {response.model}\")\n",
    "except Exception as e:\n",
    "    print(f\"\u274c API connection failed: {e}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## Part 1: The Brief\n",
    "\n",
    "### The Situation\n",
    "\n",
    "**Helios Security** is a mid-market cybersecurity vendor selling endpoint protection, SIEM, and managed detection & response. Their sales team responds to **40+ RFPs per quarter**, each containing 50\u2013200 questions spanning technical architecture, compliance certifications, pricing models, and company background.\n",
    "\n",
    "Today, each RFP takes a solutions engineer **6\u20138 hours** to complete. The process is manual: hunt through a Confluence wiki of past proposals, cross-reference product documentation, and copy-paste answers into a spreadsheet \u2014 adjusting tone and specificity for each prospect. Answers frequently **contradict each other** across questions because no one reviews the full response holistically.\n",
    "\n",
    "Helios wants an AI agent that takes in an RFP questionnaire and produces a draft response in minutes \u2014 decomposing questions, retrieving relevant source material, synthesizing polished answers, and flagging anything the human needs to review.\n",
    "\n",
    "**The goal:** Cut first-draft time from 8 hours to under 15 minutes and eliminate cross-answer inconsistencies.\n",
    "\n",
    "### The Agent Pipeline\n",
    "\n",
    "```\n",
    "\u250c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2510    \u250c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2510    \u250c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2510    \u250c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2510    \u250c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2510\n",
    "\u2502  PARSE   \u2502\u2500\u2500\u2500\u25b6\u2502 RETRIEVE \u2502\u2500\u2500\u2500\u25b6\u2502  DRAFT   \u2502\u2500\u2500\u2500\u25b6\u2502  REVIEW  \u2502\u2500\u2500\u2500\u25b6\u2502  EXPORT  \u2502\n",
    "\u2502          \u2502    \u2502          \u2502    \u2502          \u2502    \u2502          \u2502    \u2502          \u2502\n",
    "\u2502 Break    \u2502    \u2502 Search   \u2502    \u2502 Generate \u2502    \u2502 Check    \u2502    \u2502 Return   \u2502\n",
    "\u2502 into Qs  \u2502    \u2502 mock KB  \u2502    \u2502 answers  \u2502    \u2502 for      \u2502    \u2502 struct.  \u2502\n",
    "\u2502 + tag    \u2502    \u2502 via tool \u2502    \u2502 w/ cites \u2502    \u2502 contra-  \u2502    \u2502 JSON     \u2502\n",
    "\u2502 category \u2502    \u2502          \u2502    \u2502          \u2502    \u2502 dictions \u2502    \u2502          \u2502\n",
    "\u2514\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518    \u2514\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518    \u2514\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518    \u2514\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518    \u2514\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518\n",
    "```\n",
    "\n",
    "### Sample RFP Questions\n",
    "\n",
    "| ID | Category | Question |\n",
    "|----|----------|----------|\n",
    "| Q1 | Technical | Describe your platform's approach to real-time threat detection. What data sources are ingested, and what is the average detection-to-alert latency? |\n",
    "| Q2 | Compliance | List all compliance certifications your organization currently holds (SOC 2, ISO 27001, FedRAMP, etc.) and the date of most recent audit for each. |\n",
    "| Q3 | Pricing | Provide per-seat pricing for 500, 1,000, and 5,000 endpoints. Are volume discounts available? Is there a minimum contract term? |\n",
    "| Q4 | Company-Info | How many customers do you currently serve in the financial services vertical? Provide 2\u20133 reference accounts. |\n",
    "| Q5 | Technical + Compliance | How does your platform handle data residency requirements for customers operating in the EU? Describe encryption at rest and in transit. |"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## Part 2: Mock Knowledge Base (Pre-Built)\n",
    "\n",
    "Your agent needs data to retrieve from. Below is a pre-built mock knowledge base with realistic Helios Security content. **You can extend this with additional entries**, but the baseline is ready to use."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# MOCK KNOWLEDGE BASE\n",
    "# Pre-populated with realistic Helios Security content.\n",
    "# Extend with additional entries if you want richer agent behavior.\n",
    "# ============================================================\n",
    "\n",
    "KNOWLEDGE_BASE = {\n",
    "    \"threat_detection\": {\n",
    "        \"source\": \"Helios Platform Architecture Doc v4.2\",\n",
    "        \"content\": (\n",
    "            \"Helios Sentinel uses a multi-layered detection engine combining \"\n",
    "            \"signature-based matching, behavioral analysis, and ML-driven anomaly detection. \"\n",
    "            \"Data sources include endpoint telemetry (process events, file system changes, \"\n",
    "            \"network connections), cloud workload logs (AWS CloudTrail, Azure Activity Log, \"\n",
    "            \"GCP Audit Log), network flow data (NetFlow v9/IPFIX), and email gateway events. \"\n",
    "            \"Average detection-to-alert latency is 2.3 seconds for signature matches and \"\n",
    "            \"18 seconds for behavioral detections. Our SIEM correlation engine processes \"\n",
    "            \"up to 50,000 events per second per tenant.\"\n",
    "        ),\n",
    "        \"tags\": [\"technical\", \"detection\", \"latency\", \"architecture\"]\n",
    "    },\n",
    "    \"compliance_certs\": {\n",
    "        \"source\": \"Helios Compliance & Certifications Register 2025\",\n",
    "        \"content\": (\n",
    "            \"Current certifications: SOC 2 Type II (audited December 2024 by Deloitte), \"\n",
    "            \"ISO 27001:2022 (certified March 2024 by BSI), FedRAMP Moderate (authorized \"\n",
    "            \"June 2024, sponsored by DHS), HIPAA (BAA available, last assessment October 2024), \"\n",
    "            \"PCI DSS v4.0 Level 1 Service Provider (validated September 2024 by Coalfire). \"\n",
    "            \"StateRAMP authorized (January 2025). All certifications maintained on continuous \"\n",
    "            \"monitoring basis with quarterly internal audits.\"\n",
    "        ),\n",
    "        \"tags\": [\"compliance\", \"certifications\", \"audit\", \"soc2\", \"fedramp\"]\n",
    "    },\n",
    "    \"pricing_model\": {\n",
    "        \"source\": \"Helios Commercial Pricing Sheet Q1 2025\",\n",
    "        \"content\": (\n",
    "            \"Endpoint Protection Platform (EPP+EDR bundle): \"\n",
    "            \"500 endpoints: $18/seat/month ($108,000/year). \"\n",
    "            \"1,000 endpoints: $15/seat/month ($180,000/year) \u2014 17% volume discount. \"\n",
    "            \"5,000 endpoints: $11/seat/month ($660,000/year) \u2014 39% volume discount. \"\n",
    "            \"Minimum contract term: 12 months. Multi-year discounts: 2-year = additional 5%, \"\n",
    "            \"3-year = additional 10%. SIEM add-on: +$6/seat/month. \"\n",
    "            \"MDR add-on: +$12/seat/month. All pricing excludes professional services.\"\n",
    "        ),\n",
    "        \"tags\": [\"pricing\", \"commercial\", \"discount\", \"contract\"]\n",
    "    },\n",
    "    \"financial_services_customers\": {\n",
    "        \"source\": \"Helios Customer Success \u2014 Vertical Report 2024\",\n",
    "        \"content\": (\n",
    "            \"Helios currently serves 47 customers in financial services, including \"\n",
    "            \"12 banks, 8 insurance carriers, 15 asset management firms, and 12 fintech companies. \"\n",
    "            \"Reference accounts (approved for external use): \"\n",
    "            \"1) Meridian National Bank \u2014 3,200 endpoints, EPP+EDR+SIEM, deployed since 2022. \"\n",
    "            \"2) Crestview Capital Partners \u2014 850 endpoints, EPP+MDR, deployed since 2023. \"\n",
    "            \"3) Apex Insurance Group \u2014 5,100 endpoints, full platform, deployed since 2021. \"\n",
    "            \"Average NPS in financial services vertical: 72.\"\n",
    "        ),\n",
    "        \"tags\": [\"company-info\", \"customers\", \"financial-services\", \"references\"]\n",
    "    },\n",
    "    \"data_residency_eu\": {\n",
    "        \"source\": \"Helios Data Sovereignty & Privacy Whitepaper v3.1\",\n",
    "        \"content\": (\n",
    "            \"Helios supports full EU data residency through dedicated infrastructure in \"\n",
    "            \"Frankfurt (AWS eu-central-1) and Dublin (AWS eu-west-1). Customer data never \"\n",
    "            \"leaves the selected region. Encryption at rest: AES-256-GCM with customer-managed \"\n",
    "            \"keys (AWS KMS or BYOK). Encryption in transit: TLS 1.3 for all API and agent \"\n",
    "            \"communications, with certificate pinning for endpoint agents. \"\n",
    "            \"GDPR Data Processing Agreement (DPA) included in all EU contracts. \"\n",
    "            \"Annual third-party penetration testing by NCC Group. \"\n",
    "            \"Data retention: configurable per tenant, default 90 days for raw telemetry, \"\n",
    "            \"13 months for aggregated alerts.\"\n",
    "        ),\n",
    "        \"tags\": [\"technical\", \"compliance\", \"data-residency\", \"eu\", \"encryption\", \"gdpr\"]\n",
    "    },\n",
    "    \"past_rfp_detection_answer\": {\n",
    "        \"source\": \"Acme Corp RFP Response \u2014 March 2024\",\n",
    "        \"content\": (\n",
    "            \"Q: Describe your real-time threat detection capabilities. \"\n",
    "            \"A: Helios Sentinel provides sub-3-second detection for known threat patterns \"\n",
    "            \"and under 20 seconds for behavioral anomalies. Our detection engine ingests \"\n",
    "            \"endpoint telemetry, network flows, cloud audit logs, and email events. \"\n",
    "            \"The SIEM correlation engine handles 50K EPS per tenant. \"\n",
    "            \"We maintain a 99.7% true positive rate on our top 100 detection rules, \"\n",
    "            \"validated quarterly against MITRE ATT&CK framework.\"\n",
    "        ),\n",
    "        \"tags\": [\"technical\", \"detection\", \"past-rfp\"]\n",
    "    },\n",
    "    \"past_rfp_compliance_answer\": {\n",
    "        \"source\": \"NovaTech RFP Response \u2014 July 2024\",\n",
    "        \"content\": (\n",
    "            \"Q: What compliance certifications do you hold? \"\n",
    "            \"A: Helios holds SOC 2 Type II, ISO 27001, FedRAMP Moderate, PCI DSS v4.0, \"\n",
    "            \"and HIPAA compliance. All certifications are actively maintained with \"\n",
    "            \"continuous monitoring. We provide audit reports upon request under NDA. \"\n",
    "            \"Our security team of 14 full-time engineers manages compliance programs.\"\n",
    "        ),\n",
    "        \"tags\": [\"compliance\", \"certifications\", \"past-rfp\"]\n",
    "    }\n",
    "}\n",
    "\n",
    "\n",
    "def search_knowledge_base(query: str, category: Optional[str] = None) -> list[dict]:\n",
    "    \"\"\"\n",
    "    Search the mock knowledge base.\n",
    "    Returns matching entries ranked by keyword overlap.\n",
    "    \"\"\"\n",
    "    query_terms = set(query.lower().split())\n",
    "    results = []\n",
    "\n",
    "    for entry_id, entry in KNOWLEDGE_BASE.items():\n",
    "        # Score by keyword overlap with content + tags\n",
    "        entry_text = (entry[\"content\"] + \" \" + \" \".join(entry[\"tags\"])).lower()\n",
    "        overlap = len(query_terms & set(entry_text.split()))\n",
    "\n",
    "        # Boost if category matches a tag\n",
    "        if category and category.lower() in [t.lower() for t in entry[\"tags\"]]:\n",
    "            overlap += 5\n",
    "\n",
    "        if overlap > 0:\n",
    "            results.append({\n",
    "                \"id\": entry_id,\n",
    "                \"source\": entry[\"source\"],\n",
    "                \"content\": entry[\"content\"],\n",
    "                \"relevance_score\": overlap\n",
    "            })\n",
    "\n",
    "    # Sort by relevance, return top 3\n",
    "    results.sort(key=lambda x: x[\"relevance_score\"], reverse=True)\n",
    "    return results[:3]\n",
    "\n",
    "\n",
    "# Quick test\n",
    "test_results = search_knowledge_base(\"threat detection latency\", category=\"technical\")\n",
    "print(f\"\u2713 Knowledge base loaded ({len(KNOWLEDGE_BASE)} entries)\")\n",
    "print(f\"  Test search 'threat detection latency': {len(test_results)} results\")\n",
    "print(f\"  Top result: {test_results[0]['source']}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## Part 3: Tool Definition\n",
    "\n",
    "Define the `search_kb` tool so Claude can retrieve information from the knowledge base during its agent loop."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Tool definition for the Claude API\n",
    "SEARCH_KB_TOOL = {\n",
    "    \"name\": \"search_kb\",\n",
    "    \"description\": (\n",
    "        \"Search the Helios Security knowledge base for information relevant to \"\n",
    "        \"answering an RFP question. Returns up to 3 matching documents with source \"\n",
    "        \"attribution. Use this to find product docs, past proposal answers, compliance \"\n",
    "        \"records, and pricing information.\"\n",
    "    ),\n",
    "    \"input_schema\": {\n",
    "        \"type\": \"object\",\n",
    "        \"properties\": {\n",
    "            \"query\": {\n",
    "                \"type\": \"string\",\n",
    "                \"description\": \"Search query \u2014 use keywords from the RFP question\"\n",
    "            },\n",
    "            \"category\": {\n",
    "                \"type\": \"string\",\n",
    "                \"enum\": [\"technical\", \"compliance\", \"pricing\", \"company-info\"],\n",
    "                \"description\": \"Optional category filter to narrow results\"\n",
    "            }\n",
    "        },\n",
    "        \"required\": [\"query\"]\n",
    "    }\n",
    "}\n",
    "\n",
    "\n",
    "def handle_tool_call(tool_name: str, tool_input: dict) -> str:\n",
    "    \"\"\"Execute a tool call and return the result as a string.\"\"\"\n",
    "    if tool_name == \"search_kb\":\n",
    "        results = search_knowledge_base(\n",
    "            query=tool_input[\"query\"],\n",
    "            category=tool_input.get(\"category\")\n",
    "        )\n",
    "        return json.dumps(results, indent=2)\n",
    "    else:\n",
    "        return json.dumps({\"error\": f\"Unknown tool: {tool_name}\"})\n",
    "\n",
    "\n",
    "print(\"\u2713 Tool definition ready\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## Part 4: Level 0 Agent (Working Baseline)\n",
    "\n",
    "Below is a working agent that handles a **single question** end-to-end. It:\n",
    "- Sends the question to Claude with the `search_kb` tool available\n",
    "- Handles the tool use loop (Claude calls the tool \u2192 we execute it \u2192 send results back)\n",
    "- Returns a structured answer\n",
    "\n",
    "**Run this to confirm the agent loop works**, then extend it in Part 5."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "SYSTEM_PROMPT = \"\"\"You are an AI assistant helping Helios Security respond to RFP questionnaires.\n",
    "\n",
    "For each question, you must:\n",
    "1. Use the search_kb tool to find relevant source material\n",
    "2. Draft a professional, detailed answer grounded in the retrieved sources\n",
    "3. Cite your sources by name\n",
    "4. If the knowledge base doesn't contain enough information, flag the answer as low-confidence\n",
    "\n",
    "Return your answer as JSON with this structure:\n",
    "{\n",
    "    \"question_id\": \"Q1\",\n",
    "    \"category\": \"technical\",\n",
    "    \"answer\": \"Your drafted answer here...\",\n",
    "    \"sources\": [\"Source Name 1\", \"Source Name 2\"],\n",
    "    \"confidence\": \"high\" | \"medium\" | \"low\",\n",
    "    \"flags\": [\"any concerns or notes for human review\"]\n",
    "}\n",
    "\n",
    "Be specific, professional, and concise. Use concrete numbers from the source material.\"\"\"\n",
    "\n",
    "\n",
    "def answer_single_question(\n",
    "    question_id: str,\n",
    "    question_text: str,\n",
    "    category: str,\n",
    "    model: str = \"claude-sonnet-4-20250514\",\n",
    ") -> dict:\n",
    "    \"\"\"\n",
    "    Level 0 agent: answers a single RFP question with tool use.\n",
    "    Handles the full tool use loop.\n",
    "    \"\"\"\n",
    "    messages = [\n",
    "        {\n",
    "            \"role\": \"user\",\n",
    "            \"content\": (\n",
    "                f\"Answer this RFP question.\\n\\n\"\n",
    "                f\"Question ID: {question_id}\\n\"\n",
    "                f\"Category: {category}\\n\"\n",
    "                f\"Question: {question_text}\\n\\n\"\n",
    "                f\"Search the knowledge base for relevant information, then draft your answer.\"\n",
    "            )\n",
    "        }\n",
    "    ]\n",
    "\n",
    "    # Agent loop: keep going until Claude stops calling tools\n",
    "    max_turns = 5  # Safety limit\n",
    "    for turn in range(max_turns):\n",
    "        response = client.messages.create(\n",
    "            model=model,\n",
    "            max_tokens=2048,\n",
    "            system=SYSTEM_PROMPT,\n",
    "            messages=messages,\n",
    "            tools=[SEARCH_KB_TOOL],\n",
    "        )\n",
    "\n",
    "        # If Claude is done (no more tool calls), extract the answer\n",
    "        if response.stop_reason == \"end_turn\":\n",
    "            # Find the text block with the JSON answer\n",
    "            for block in response.content:\n",
    "                if block.type == \"text\":\n",
    "                    try:\n",
    "                        # Try to parse JSON from the response\n",
    "                        text = block.text\n",
    "                        # Handle markdown code blocks\n",
    "                        if \"```json\" in text:\n",
    "                            text = text.split(\"```json\")[1].split(\"```\")[0]\n",
    "                        elif \"```\" in text:\n",
    "                            text = text.split(\"```\")[1].split(\"```\")[0]\n",
    "                        return json.loads(text.strip())\n",
    "                    except json.JSONDecodeError:\n",
    "                        return {\"raw_response\": block.text, \"parse_error\": True}\n",
    "            break\n",
    "\n",
    "        # If Claude wants to use a tool, execute it and continue\n",
    "        if response.stop_reason == \"tool_use\":\n",
    "            # Add assistant's response to message history\n",
    "            messages.append({\"role\": \"assistant\", \"content\": response.content})\n",
    "\n",
    "            # Execute each tool call and collect results\n",
    "            tool_results = []\n",
    "            for block in response.content:\n",
    "                if block.type == \"tool_use\":\n",
    "                    result = handle_tool_call(block.name, block.input)\n",
    "                    tool_results.append({\n",
    "                        \"type\": \"tool_result\",\n",
    "                        \"tool_use_id\": block.id,\n",
    "                        \"content\": result,\n",
    "                    })\n",
    "\n",
    "            messages.append({\"role\": \"user\", \"content\": tool_results})\n",
    "\n",
    "    return {\"error\": \"Max turns reached without completing\"}\n",
    "\n",
    "\n",
    "print(\"\u2713 Level 0 agent defined\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Test: Answer Q1\n",
    "print(\"Answering Q1 (threat detection)...\")\n",
    "result = answer_single_question(\n",
    "    question_id=\"Q1\",\n",
    "    question_text=(\n",
    "        \"Describe your platform's approach to real-time threat detection. \"\n",
    "        \"What data sources are ingested, and what is the average detection-to-alert latency?\"\n",
    "    ),\n",
    "    category=\"technical\",\n",
    ")\n",
    "\n",
    "print(json.dumps(result, indent=2))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## Part 5: \ud83d\udee0\ufe0f YOUR TASK \u2014 Multi-Question Agent\n",
    "\n",
    "The Level 0 agent handles one question at a time. Your job is to build a **full pipeline** that:\n",
    "\n",
    "1. **Accepts a list of RFP questions** (the full questionnaire)\n",
    "2. **Processes each question** through the agent loop\n",
    "3. **Collects all answers** into a structured response\n",
    "4. **Exports as JSON** with all required fields\n",
    "\n",
    "### Approaches to Consider\n",
    "\n",
    "- **Sequential:** Process questions one by one using `answer_single_question()`. Simple, reliable, but slower.\n",
    "- **Batch prompt:** Send all questions to Claude in a single prompt and let it call the tool multiple times. Faster, but harder to control.\n",
    "- **Hybrid:** Parse and categorize first, then process by category to reuse retrieved context.\n",
    "\n",
    "### Starter Questions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# RFP Questionnaire\n",
    "RFP_QUESTIONS = [\n",
    "    {\n",
    "        \"id\": \"Q1\",\n",
    "        \"category\": \"technical\",\n",
    "        \"text\": (\n",
    "            \"Describe your platform's approach to real-time threat detection. \"\n",
    "            \"What data sources are ingested, and what is the average detection-to-alert latency?\"\n",
    "        ),\n",
    "    },\n",
    "    {\n",
    "        \"id\": \"Q2\",\n",
    "        \"category\": \"compliance\",\n",
    "        \"text\": (\n",
    "            \"List all compliance certifications your organization currently holds \"\n",
    "            \"(SOC 2, ISO 27001, FedRAMP, etc.) and the date of most recent audit for each.\"\n",
    "        ),\n",
    "    },\n",
    "    {\n",
    "        \"id\": \"Q3\",\n",
    "        \"category\": \"pricing\",\n",
    "        \"text\": (\n",
    "            \"Provide per-seat pricing for 500, 1,000, and 5,000 endpoints. \"\n",
    "            \"Are volume discounts available? Is there a minimum contract term?\"\n",
    "        ),\n",
    "    },\n",
    "    {\n",
    "        \"id\": \"Q4\",\n",
    "        \"category\": \"company-info\",\n",
    "        \"text\": (\n",
    "            \"How many customers do you currently serve in the financial services vertical? \"\n",
    "            \"Provide 2\u20133 reference accounts.\"\n",
    "        ),\n",
    "    },\n",
    "    {\n",
    "        \"id\": \"Q5\",\n",
    "        \"category\": \"technical\",\n",
    "        \"text\": (\n",
    "            \"How does your platform handle data residency requirements for customers \"\n",
    "            \"operating in the EU? Describe encryption at rest and in transit.\"\n",
    "        ),\n",
    "    },\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# \ud83d\udee0\ufe0f YOUR CODE: Build the multi-question agent\n",
    "# ============================================================\n",
    "#\n",
    "# Process all RFP_QUESTIONS and collect structured responses.\n",
    "#\n",
    "# Your output should be a list of answer objects, each containing:\n",
    "#   - question_id\n",
    "#   - category\n",
    "#   - answer\n",
    "#   - sources\n",
    "#   - confidence (high / medium / low)\n",
    "#   - flags (list of concerns for human review)\n",
    "#\n",
    "# HINT: The simplest approach is a loop over answer_single_question().\n",
    "# More advanced: modify the system prompt to handle batches.\n",
    "# ============================================================\n",
    "\n",
    "def process_rfp(questions: list[dict]) -> list[dict]:\n",
    "    \"\"\"Process a full RFP questionnaire and return structured answers.\"\"\"\n",
    "    answers = []\n",
    "\n",
    "    # TODO: Your implementation here\n",
    "    # Option 1 (simple): Loop through questions, call answer_single_question for each\n",
    "    # Option 2 (advanced): Send all questions in one prompt with batch processing\n",
    "\n",
    "    pass  # Replace with your implementation\n",
    "\n",
    "    return answers\n",
    "\n",
    "\n",
    "# Run it\n",
    "print(\"Processing RFP...\")\n",
    "all_answers = process_rfp(RFP_QUESTIONS)\n",
    "\n",
    "# Display results\n",
    "if all_answers:\n",
    "    for ans in all_answers:\n",
    "        q_id = ans.get('question_id', '?')\n",
    "        conf = ans.get('confidence', '?')\n",
    "        print(f\"  {q_id}: confidence={conf}, sources={len(ans.get('sources', []))}\")\n",
    "    print(f\"\\n\u2713 Processed {len(all_answers)} questions\")\n",
    "else:\n",
    "    print(\"\u274c No answers returned \u2014 implement process_rfp() above\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## Part 6: \ud83d\udee0\ufe0f YOUR TASK \u2014 Consistency Review Step\n",
    "\n",
    "The customer specifically asked for **cross-answer consistency checking**. Answers drafted individually often contradict each other (e.g., Q2 says \"FedRAMP authorized June 2024\" but Q5 says \"FedRAMP certified in 2023\").\n",
    "\n",
    "Build a review step that:\n",
    "1. Takes all drafted answers as input\n",
    "2. Identifies potential contradictions or inconsistencies\n",
    "3. Flags issues for human review\n",
    "\n",
    "**This is what separates a good agent from a great one.** In real deployments, consistency is the #1 quality issue in automated RFP responses."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# \ud83d\udee0\ufe0f YOUR CODE: Consistency review step\n",
    "# ============================================================\n",
    "#\n",
    "# Send all answers to Claude for cross-answer review.\n",
    "# Look for: contradictions, inconsistent data points, tone mismatches.\n",
    "#\n",
    "# HINT: Format all answers as a single prompt and ask Claude to\n",
    "# identify any inconsistencies. No tool use needed for this step.\n",
    "# ============================================================\n",
    "\n",
    "def review_answers(answers: list[dict]) -> dict:\n",
    "    \"\"\"\n",
    "    Review all drafted answers for cross-question consistency.\n",
    "    Returns a review report with any flagged issues.\n",
    "    \"\"\"\n",
    "\n",
    "    # TODO: Your implementation here\n",
    "    # 1. Format all answers into a single prompt\n",
    "    # 2. Ask Claude to identify contradictions, inconsistencies, tone issues\n",
    "    # 3. Return a structured review report\n",
    "\n",
    "    pass  # Replace with your implementation\n",
    "\n",
    "\n",
    "# Run review on your answers\n",
    "if all_answers:\n",
    "    print(\"Running consistency review...\")\n",
    "    review = review_answers(all_answers)\n",
    "    print(json.dumps(review, indent=2))\n",
    "else:\n",
    "    print(\"\u26a0\ufe0f No answers to review yet \u2014 complete Part 5 first\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## Part 7: Export Final Output\n",
    "\n",
    "Package your agent's output as clean JSON \u2014 the deliverable Helios would actually receive."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Build the final export\n",
    "final_output = {\n",
    "    \"rfp_name\": \"Sample RFP \u2014 Agent Engineering Challenge\",\n",
    "    \"total_questions\": len(RFP_QUESTIONS),\n",
    "    \"answers\": all_answers if all_answers else [],\n",
    "    \"review\": review if 'review' in dir() and review else \"Review not completed\",\n",
    "    \"metadata\": {\n",
    "        \"model\": \"claude-sonnet-4-20250514\",\n",
    "        \"knowledge_base_entries\": len(KNOWLEDGE_BASE),\n",
    "    }\n",
    "}\n",
    "\n",
    "print(json.dumps(final_output, indent=2))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## Part 8: \u2b50 STRETCH \u2014 Eval Assertions\n",
    "\n",
    "*This section is optional and unscored, but demonstrates rigor.*\n",
    "\n",
    "Build assertions that validate your agent's output quality. Good evals test real failure modes, not just happy paths.\n",
    "\n",
    "### What to Test\n",
    "\n",
    "| Dimension | Example Assertion |\n",
    "|-----------|-------------------|\n",
    "| **Accuracy** | Q3 pricing answer contains \"$18/seat/month\" for 500 endpoints |\n",
    "| **Source attribution** | Every answer has at least one source cited |\n",
    "| **Consistency** | Q2 and Q5 don't contradict each other on certification dates |\n",
    "| **Confidence calibration** | Questions with no KB match are flagged as low-confidence |\n",
    "| **Edge cases** | What happens with an ambiguous or unanswerable question? |"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# \u2b50 STRETCH: Write eval assertions\n",
    "# ============================================================\n",
    "\n",
    "def run_evals(answers: list[dict]) -> dict:\n",
    "    \"\"\"Run quality assertions against agent output.\"\"\"\n",
    "    results = {\"passed\": 0, \"failed\": 0, \"details\": []}\n",
    "\n",
    "    for ans in answers:\n",
    "        # Example assertion: every answer has sources\n",
    "        has_sources = len(ans.get(\"sources\", [])) > 0\n",
    "        results[\"details\"].append({\n",
    "            \"question\": ans.get(\"question_id\"),\n",
    "            \"assertion\": \"has_sources\",\n",
    "            \"passed\": has_sources,\n",
    "        })\n",
    "        if has_sources:\n",
    "            results[\"passed\"] += 1\n",
    "        else:\n",
    "            results[\"failed\"] += 1\n",
    "\n",
    "    # TODO: Add more assertions\n",
    "    # - Check that pricing answer contains specific numbers\n",
    "    # - Check that confidence is a valid value\n",
    "    # - Check for cross-answer consistency\n",
    "    # - Test an edge case question (e.g., a question with no KB match)\n",
    "\n",
    "    return results\n",
    "\n",
    "\n",
    "if all_answers:\n",
    "    eval_results = run_evals(all_answers)\n",
    "    print(f\"Eval Results: {eval_results['passed']} passed, {eval_results['failed']} failed\")\n",
    "    for detail in eval_results[\"details\"]:\n",
    "        status = \"\u2713\" if detail[\"passed\"] else \"\u274c\"\n",
    "        print(f\"  {status} {detail['question']}: {detail['assertion']}\")\n",
    "else:\n",
    "    print(\"\u26a0\ufe0f Complete Part 5 first\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "## \ud83c\udfc1 Demo Prep\n",
    "\n",
    "Your team has **3 minutes** to present. Suggested structure:\n",
    "\n",
    "| Segment | Duration | Content |\n",
    "|---------|----------|--------|\n",
    "| Architecture | ~45 sec | How you structured the agent, what design decisions you made |\n",
    "| Live run | ~1 min | Run your agent on the RFP, walk through the output |\n",
    "| Retrospective | ~1 min | What worked, what broke, what you'd improve with more time |\n",
    "\n",
    "### Questions to answer in your demo:\n",
    "1. How did you handle the tool use loop? Sequential or batch?\n",
    "2. What does your review step actually catch?\n",
    "3. What would break if you deployed this to production? What's missing?\n",
    "4. If you had another hour, what would you build first?"
   ]
  }
 ],
 "metadata": {
  "colab": {
   "provenance": [],
   "toc_visible": true
  },
  "kernelspec": {
   "display_name": "Python 3",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}